### ISSUE TITLE
The path part doesn't show

### ISSUE THREAD

**Issue by w3ntao** [pure-fish/pure#166] opened 2019-04-19 12:11 UTC
## Env

**Pure**

    echo $pure_version
2.1.5

**Fish**

    fish --version
fish, version 3.0.2

**OS/distribution**

    lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

The path part doesn't show:

![Screenshot from 2019-04-19 14-02-02](https://user-images.githubusercontent.com/6308795/56423553-e9ec8680-62ac-11e9-8799-9755444376ec.png)

**Comment by edouard-lopez** [comment] 2019-04-19 14:39
Could you try select the line on top of the prompt to see if it's empty?

Also a different theme might work better. If so, you can adjust color by overriding 	`conf.d/pure.fish` variables in your `~/.config/fish/config.fish`

**Comment by wentaocn** [comment] 2019-04-19 14:55
Hi @edouard-lopez , I tried copy the path line to some editor and got nothing, changed a few theme and still seeing nothing. Looks like it's indeed empty.

**Comment by wentaocn** [comment] 2019-04-20 14:28
It's working now.
I can't reproduce this bug any more...

**Comment by wentaocn** [comment] 2019-05-18 09:44
Having exact the same problem again (with Debian/buster).
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux buster/sid
Release:        testing
Codename:       buster
```

**Comment by edouard-lopez** [comment] 2019-05-19 22:17
Could you try to call directly the function `_pure_prompt_first_line`, the one responsible to print this line:

    source $__fish_config_dir/functions/_pure_prompt_first_line.fish
    echo output: (_pure_prompt_first_line)

**Comment by ozelotjp** [comment] 2019-09-26 07:41
maybe: it will be solved by installing git

<details>
<summary>How to reproduce problem</summary>

```bash
# Run docker
docker run --rm -it centos:7

# Install fish
curl --location --output /etc/yum.repos.d/shells:fish:release:3.repo https://download.opensuse.org/repositories/shells:fish:release:3/RHEL_7/shells:fish:release:3.repo
yum install -y fish

# Launch fish
fish

# Install fisher
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

# Install pure
fisher add rafaelrinaldi/pure
```

</details>

**Comment by DrPhil** [comment] 2019-10-15 13:53
I can recreate this problem by having `_pure_prompt_first_line` be longer than what fits in my terminal without wrapping. You can test by creating a git branch with a very long name like I do in this picture. If I then resize my terminal the prompt will show.

![image](https://user-images.githubusercontent.com/184889/66837296-0ec36d00-ef63-11e9-9074-02e58f52749f.png)

Maybe `_pure_print_prompt` should try to cut the prompt, or try to shorten the branch name if it is long. Unfortunately `string sub -l $COLUMNS $prompt` is not good enough. (e.g. set_color or emojis will break that approximation.) Anyone with more insight in how to cut a fish string based on rendered length?

**Comment by schrodincat** [comment] 2019-12-14 14:14
> Unfortunately string sub -l $COLUMNS $prompt is not good enough (e.g. set_color or emojis will break that approximation).

We take into consideration ANSI colors already (see https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_string_width.fish), however, there is no way to tell the printed length beforehand exactly.

I've opened another issue to discuss this: https://github.com/rafaelrinaldi/pure/issues/198.

**Comment by kidonng** [comment] 2020-07-07 14:09
@ozelotjp Running into this issue, installing Git solved it.

**Comment by edouard-lopez** [comment] 2020-12-27 00:20
I'm happy to review PR for this one :)

**Comment by soredake** [comment] 2022-05-28 09:13
I'm getting the same problem in fedora kde 36 vm with konsole.

**Comment by pauleikis** [comment] 2023-01-04 11:03
I can confirm that I had the same issue and installing git solves it

**Comment by edouard-lopez** [comment] 2023-01-04 17:19
Using @ozelotjp I'm able to reproduce with :

```
❯ echo $pure_version 
> echo 4.4.0
4.4.0
```

## Debugging

```
❯ set fish_trace 1


❯ _pure_prompt_first_line
> _pure_prompt_first_line
--> if
--> type -q --no-functions git
---> return 1
--> end if
```

Sound like `git` is missing, and we [aborted the whole prompt in that case](https://github.com/pure-fish/pure/blob/1aca7e7a45768af2f5196daa6d37dd2a1d2bb75a/functions/_pure_prompt_first_line.fish#L6-L8) and we even have [a test case for that](https://github.com/pure-fish/pure/blob/1aca7e7a45768af2f5196daa6d37dd2a1d2bb75a/tests/_pure_prompt_first_line.test.fish#L35-L49)
```
❯ type git
> type git
type: Could not find 'git'
```

So installing with `git` probably meant you installed it, thus resolving the issue. I will update the behaviour to skip git-related prompt when it's missing from the system, there is no need to require it anyway. See #313

**Closed** 2023-01-31 21:32 UTC
Labels: 🐛 bug, 🙏 help wanted
